Algoritmo "Meu primeiro algoritmo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/06/2024
Var
// Seção de Declarações das variáveis 
      pontos: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
          pontos <- 100
          escreva("Campeão:", pontos)

Fimalgoritmo